services:
  postgres:
    image: postgres:latest
    container_name: clientesapi_postgres
    restart: always
    environment:
      POSTGRES_DB: clientesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
